/**
 * ItemModel3D — Procedural Three.js model for a crafted Item.
 * Geometry generated by item category, colored by primary material.
 * PanResponder drives Y/X rotation. Falls back to a 2D colored shape when WebGL unavailable.
 */
import React, { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { PanResponder, Platform, StyleSheet, Text, View } from 'react-native';
import { Feather } from '@expo/vector-icons';
import Constants from 'expo-constants';
import type { Item, ItemCategory } from '@/types/game';

// expo-gl crashes Expo Go on Android at import time — lazy-require only in standalone/web
const IS_EXPO_GO =
  Platform.OS !== 'web' &&
  ((Constants.appOwnership as string) === 'expo' ||
    Constants.executionEnvironment === 'storeClient');

// eslint-disable-next-line @typescript-eslint/no-explicit-any
let GLView: React.ComponentType<any> | null = null;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
let THREE: any = null;
if (!IS_EXPO_GO) {
  try { GLView = require('expo-gl').GLView; } catch { GLView = null; }
  try { THREE = require('three'); } catch { THREE = null; }
}
type ExpoWebGLRenderingContext = any;

// ─── WebGL check ─────────────────────────────────────────────────────────────
function hasWebGL(): boolean {
  if (Platform.OS !== 'web') return true;
  try {
    const c = document.createElement('canvas');
    return !!(window.WebGLRenderingContext && (c.getContext('webgl') || c.getContext('experimental-webgl')));
  } catch { return false; }
}

// ─── Category → geometry ─────────────────────────────────────────────────────
function buildItemGroup(category: ItemCategory, material: any): any {
  const g = new THREE.Group();
  const m = material;

  switch (category) {
    case 'sword': {
      const blade = new THREE.Mesh(new THREE.BoxGeometry(0.09, 1.9, 0.05), m);
      blade.position.y = 0.3;
      const guard = new THREE.Mesh(new THREE.BoxGeometry(0.62, 0.07, 0.09), m);
      guard.position.y = -0.52;
      const pommel = new THREE.Mesh(new THREE.SphereGeometry(0.085, 8, 8), m);
      pommel.position.y = -0.92;
      const handle = new THREE.Mesh(new THREE.CylinderGeometry(0.038, 0.038, 0.38, 8), m);
      handle.position.y = -0.72;
      g.add(blade, guard, handle, pommel);
      break;
    }
    case 'axe': {
      const handle = new THREE.Mesh(new THREE.CylinderGeometry(0.038, 0.038, 1.6, 8), m);
      const headMat = material.clone();
      const head = new THREE.Mesh(new THREE.BoxGeometry(0.48, 0.55, 0.09), headMat);
      head.position.set(0.22, 0.5, 0);
      const cheek = new THREE.Mesh(new THREE.BoxGeometry(0.28, 0.28, 0.09), headMat);
      cheek.position.set(-0.12, 0.62, 0);
      cheek.rotation.z = 0.4;
      g.add(handle, head, cheek);
      break;
    }
    case 'hammer': {
      const handle = new THREE.Mesh(new THREE.CylinderGeometry(0.038, 0.038, 1.5, 8), m);
      const head = new THREE.Mesh(new THREE.BoxGeometry(0.34, 0.26, 0.24), m);
      head.position.y = 0.65;
      g.add(handle, head);
      break;
    }
    case 'lance': {
      const shaft = new THREE.Mesh(new THREE.CylinderGeometry(0.025, 0.025, 1.9, 8), m);
      const tip = new THREE.Mesh(new THREE.ConeGeometry(0.065, 0.45, 8), m);
      tip.position.y = 1.15;
      g.add(shaft, tip);
      break;
    }
    case 'shield': {
      const face = new THREE.Mesh(new THREE.BoxGeometry(0.78, 0.95, 0.085), m);
      const boss = new THREE.Mesh(new THREE.SphereGeometry(0.1, 8, 8), m);
      boss.position.z = 0.08;
      const rimH = new THREE.Mesh(new THREE.BoxGeometry(0.8, 0.065, 0.14), m);
      rimH.position.y = 0.48;
      const rimHb = new THREE.Mesh(new THREE.BoxGeometry(0.8, 0.065, 0.14), m);
      rimHb.position.y = -0.48;
      g.add(face, boss, rimH, rimHb);
      break;
    }
    case 'armor': {
      const body = new THREE.Mesh(new THREE.CylinderGeometry(0.28, 0.22, 0.72, 10), m);
      body.position.y = 0.06;
      const shL = new THREE.Mesh(new THREE.SphereGeometry(0.16, 8, 8), m);
      shL.position.set(-0.38, 0.38, 0);
      const shR = new THREE.Mesh(new THREE.SphereGeometry(0.16, 8, 8), m);
      shR.position.set(0.38, 0.38, 0);
      const neck = new THREE.Mesh(new THREE.CylinderGeometry(0.11, 0.18, 0.18, 8), m);
      neck.position.y = 0.44;
      g.add(body, shL, shR, neck);
      break;
    }
    case 'helmet': {
      const dome = new THREE.Mesh(new THREE.SphereGeometry(0.35, 12, 12, 0, Math.PI * 2, 0, Math.PI * 0.62), m);
      dome.position.y = 0.12;
      const brim = new THREE.Mesh(new THREE.CylinderGeometry(0.42, 0.38, 0.07, 12), m);
      brim.position.y = -0.09;
      const visor = new THREE.Mesh(new THREE.BoxGeometry(0.28, 0.065, 0.16), m);
      visor.position.set(0, 0.08, 0.32);
      g.add(dome, brim, visor);
      break;
    }
    case 'ring': {
      const band = new THREE.Mesh(new THREE.TorusGeometry(0.28, 0.062, 10, 24), m);
      const gem = new THREE.Mesh(new THREE.OctahedronGeometry(0.1), m);
      gem.position.set(0, 0.34, 0);
      g.add(band, gem);
      break;
    }
    case 'amulet': {
      const pendant = new THREE.Mesh(new THREE.OctahedronGeometry(0.22), m);
      const chain = new THREE.Mesh(new THREE.TorusGeometry(0.44, 0.022, 6, 30), m);
      chain.rotation.x = Math.PI / 2;
      chain.position.y = 0.28;
      g.add(pendant, chain);
      break;
    }
    case 'tool': {
      const handle = new THREE.Mesh(new THREE.CylinderGeometry(0.032, 0.032, 1.4, 8), m);
      const head = new THREE.Mesh(new THREE.BoxGeometry(0.22, 0.28, 0.18), m);
      head.position.set(0.14, 0.62, 0);
      head.rotation.z = 0.3;
      const pick = new THREE.Mesh(new THREE.ConeGeometry(0.048, 0.32, 6), m);
      pick.rotation.z = Math.PI / 2;
      pick.position.set(0.36, 0.58, 0);
      g.add(handle, head, pick);
      break;
    }
    case 'decoration': {
      const base = new THREE.Mesh(new THREE.CylinderGeometry(0.22, 0.28, 0.12, 12), m);
      base.position.y = -0.5;
      const body = new THREE.Mesh(new THREE.SphereGeometry(0.28, 12, 12), m);
      const crown = new THREE.Mesh(new THREE.ConeGeometry(0.12, 0.34, 6), m);
      crown.position.y = 0.46;
      g.add(base, body, crown);
      break;
    }
    default: {
      const obj = new THREE.Mesh(new THREE.OctahedronGeometry(0.38), m);
      g.add(obj);
    }
  }
  return g;
}

// ─── Color from material string ───────────────────────────────────────────────
function colorForMaterial(matId: string): number {
  const map: Record<string, number> = {
    iron: 0x7A7A8C, copper: 0xB87333, wood: 0x8B6B3D, stone: 0x9E9E9E,
    bronze: 0xCD7F32, steel: 0x5C6B8A, silver: 0xC0C0C0, gold_ore: 0xFFD700,
    mithril: 0x6699CC, obsidian: 0x2A1828, adamantium: 0x5A2F8A, dragon_scale: 0x8B1010,
    platinum: 0xE8E8F0,
  };
  return map[matId] ?? 0x6B5A3E;
}

// ─── 2D fallback ─────────────────────────────────────────────────────────────
function CategoryFallback({ category, color }: { category: ItemCategory; color: string }) {
  const icons: Record<ItemCategory, string> = {
    sword: 'scissors', axe: 'scissors', hammer: 'tool', lance: 'triangle',
    shield: 'shield', armor: 'shield', helmet: 'circle',
    ring: 'disc', amulet: 'star', dagger: 'scissors', crown: 'award',
    tool: 'tool', decoration: 'star',
  };
  return (
    <View style={[styles.fallback, { backgroundColor: `${color}18` }]}>
      <Feather
        name={(icons[category] ?? 'tool') as any}
        size={36}
        color={color}
      />
    </View>
  );
}

// ─── Main component ───────────────────────────────────────────────────────────
interface Props {
  item: Item;
  primaryMaterialId?: string;
  height?: number;
}

export default function ItemModel3D({ item, primaryMaterialId, height = 200 }: Props) {
  // Expo Go: expo-gl absent → 2D fallback (IS_EXPO_GO is constant → consistent hooks)
  const matHex0 = '#' + (colorForMaterial(primaryMaterialId ?? item.materials[0] ?? 'iron')).toString(16).padStart(6, '0');
  if (IS_EXPO_GO || !GLView || !THREE) {
    return <CategoryFallback category={item.category} color={matHex0} />;
  }
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const [webglOk] = useState(hasWebGL);
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const rotX = useRef(0.18);
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const rotY = useRef(-0.35);
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const rotRef = useRef<any>(null);
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const cleanupRef = useRef<(() => void) | null>(null);
  // eslint-disable-next-line react-hooks/rules-of-hooks
  const matColor = useMemo(
    () => colorForMaterial(primaryMaterialId ?? item.materials[0] ?? 'iron'),
    [primaryMaterialId, item.materials],
  );
  const matHex = '#' + matColor.toString(16).padStart(6, '0');

  useEffect(() => () => { cleanupRef.current?.(); }, []);

  const panResponder = useRef(
    PanResponder.create({
      onStartShouldSetPanResponder: () => true,
      onPanResponderMove: (_e, gs) => {
        rotY.current += gs.dx * 0.012;
        rotX.current += gs.dy * 0.009;
        rotX.current = Math.max(-1.2, Math.min(1.2, rotX.current));
        if (rotRef.current) {
          rotRef.current.rotation.y = rotY.current;
          rotRef.current.rotation.x = rotX.current;
        }
      },
    }),
  ).current;

  const onContextCreate = useCallback((gl: ExpoWebGLRenderingContext) => {
    const W = gl.drawingBufferWidth;
    const H = gl.drawingBufferHeight;
    if (!(gl as any).canvas) {
      (gl as any).canvas = { width: W, height: H, style: {}, addEventListener: () => {}, removeEventListener: () => {}, dispatchEvent: () => false, clientWidth: W, clientHeight: H };
    }

    let renderer: any;
    try {
      renderer = new THREE.WebGLRenderer({ canvas: (gl as any).canvas, context: gl as unknown as WebGL2RenderingContext, antialias: true });
    } catch {
      renderer = new THREE.WebGLRenderer({ context: gl as unknown as WebGL2RenderingContext, antialias: false });
    }
    renderer.setPixelRatio(1);
    renderer.setSize(W, H);
    renderer.setClearColor(0x16101E);

    const scene = new THREE.Scene();
    const camera = new THREE.PerspectiveCamera(48, W / H, 0.1, 40);
    camera.position.set(0, 0, 3.6);

    scene.add(new THREE.AmbientLight(0x3A2A40, 0.55));
    const key = new THREE.DirectionalLight(0xF2E4C4, 1.2);
    key.position.set(3, 4, 5);
    scene.add(key);
    const fill = new THREE.PointLight(0xD4851A, 0.7, 10);
    fill.position.set(-2, 1, 2);
    scene.add(fill);
    const rim = new THREE.PointLight(0x4466AA, 0.5, 8);
    rim.position.set(1, -2, -3);
    scene.add(rim);

    const mat = new THREE.MeshStandardMaterial({ color: matColor, roughness: 0.32, metalness: 0.78 });
    const group = buildItemGroup(item.category, mat);
    group.rotation.y = rotY.current;
    group.rotation.x = rotX.current;
    rotRef.current = group;
    scene.add(group);

    let rafId: number;
    let t = 0;
    const animate = () => {
      rafId = requestAnimationFrame(animate);
      t += 0.016;
      fill.intensity = 0.65 + Math.sin(t * 1.4) * 0.08;
      renderer.render(scene, camera);
      gl.endFrameEXP();
    };
    animate();

    cleanupRef.current = () => {
      cancelAnimationFrame(rafId);
      renderer.dispose();
      rotRef.current = null;
    };
  }, [matColor, item.category]); // eslint-disable-line react-hooks/exhaustive-deps

  if (!webglOk) {
    return <CategoryFallback category={item.category} color={matHex} />;
  }

  return (
    <View style={{ height }} {...panResponder.panHandlers}>
      <GLView style={StyleSheet.absoluteFill} onContextCreate={onContextCreate} />
      <Text style={styles.dragHint}>↔ Glisser pour tourner</Text>
    </View>
  );
}

const styles = StyleSheet.create({
  fallback: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  fallbackEmoji: { fontSize: 64 },
  dragHint: { position: 'absolute', bottom: 6, right: 10, fontSize: 10, color: 'rgba(255,255,255,0.3)' },
});
