// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/templates/GothicFintechHomeScreen-ZvaDD-/App.tsx": () => import("../components/mockups/templates/GothicFintechHomeScreen-ZvaDD-/App.tsx"),
  "./components/mockups/templates/JapaneseOmakaseLandingPage-fsCXHp/App.tsx": () => import("../components/mockups/templates/JapaneseOmakaseLandingPage-fsCXHp/App.tsx"),
  "./components/mockups/templates/JapaneseOmakaseLandingPage-igh5M2/App.tsx": () => import("../components/mockups/templates/JapaneseOmakaseLandingPage-igh5M2/App.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-A9loZb/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-A9loZb/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-Fgm5s2/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-Fgm5s2/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-agOGHc/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-agOGHc/Lp14.tsx"),
  "./components/mockups/templates/MonochromeLandscapePhotographyPortfolio-wcliem/Lp14.tsx": () => import("../components/mockups/templates/MonochromeLandscapePhotographyPortfolio-wcliem/Lp14.tsx")
};
